name: Build Package

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  Publish:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: build code
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: build project
        run: npm ci

      - name: test project
        run: npm test
